# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hamilok/projects/funnel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hamilok/projects/funnel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hamilok/projects/funnel/CMakeFiles /home/hamilok/projects/funnel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hamilok/projects/funnel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named funnel

# Build rule for target.
funnel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 funnel
.PHONY : funnel

# fast build rule for target.
funnel/fast:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/build
.PHONY : funnel/fast

src/checksum.o: src/checksum.cpp.o
.PHONY : src/checksum.o

# target to build an object file
src/checksum.cpp.o:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/checksum.cpp.o
.PHONY : src/checksum.cpp.o

src/checksum.i: src/checksum.cpp.i
.PHONY : src/checksum.i

# target to preprocess a source file
src/checksum.cpp.i:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/checksum.cpp.i
.PHONY : src/checksum.cpp.i

src/checksum.s: src/checksum.cpp.s
.PHONY : src/checksum.s

# target to generate assembly for a file
src/checksum.cpp.s:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/checksum.cpp.s
.PHONY : src/checksum.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network_v4.o: src/network_v4.cpp.o
.PHONY : src/network_v4.o

# target to build an object file
src/network_v4.cpp.o:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/network_v4.cpp.o
.PHONY : src/network_v4.cpp.o

src/network_v4.i: src/network_v4.cpp.i
.PHONY : src/network_v4.i

# target to preprocess a source file
src/network_v4.cpp.i:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/network_v4.cpp.i
.PHONY : src/network_v4.cpp.i

src/network_v4.s: src/network_v4.cpp.s
.PHONY : src/network_v4.s

# target to generate assembly for a file
src/network_v4.cpp.s:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/network_v4.cpp.s
.PHONY : src/network_v4.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/zone_manager.o: src/zone_manager.cpp.o
.PHONY : src/zone_manager.o

# target to build an object file
src/zone_manager.cpp.o:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/zone_manager.cpp.o
.PHONY : src/zone_manager.cpp.o

src/zone_manager.i: src/zone_manager.cpp.i
.PHONY : src/zone_manager.i

# target to preprocess a source file
src/zone_manager.cpp.i:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/zone_manager.cpp.i
.PHONY : src/zone_manager.cpp.i

src/zone_manager.s: src/zone_manager.cpp.s
.PHONY : src/zone_manager.s

# target to generate assembly for a file
src/zone_manager.cpp.s:
	$(MAKE) -f CMakeFiles/funnel.dir/build.make CMakeFiles/funnel.dir/src/zone_manager.cpp.s
.PHONY : src/zone_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... funnel"
	@echo "... rebuild_cache"
	@echo "... src/checksum.o"
	@echo "... src/checksum.i"
	@echo "... src/checksum.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network_v4.o"
	@echo "... src/network_v4.i"
	@echo "... src/network_v4.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/zone_manager.o"
	@echo "... src/zone_manager.i"
	@echo "... src/zone_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

